# Hands
MAIN_HAND = "Left"
OFF_HAND = "Right"

# Gestures
LDM_SET_GESTURE = "Thumb_Up"
QUIT_GESTURE = "Thumb_Down"
RIGHT_CLICK_GESTURE = "Open_Palm"

# Display Window
WIN_NAME = "gameee"
WINDOW_HEIGHT = 168
WINDOW_WIDTH = 224

# CPS
LEFT_CPS = 6
RIGHT_CPS = 3
CPS_MAX_RAND_FACTOR = 0.2

# THRESHOLD
LANDMARK_DELTA_THRESHOLD = 0.05
PINCH_THRESHOLD = 6
